### ISSUE TITLE
Is Pandas 2+ a necessary requirement?

### ISSUE THREAD

**Issue by rmpinchback** [jenskeiner/exchange_calendars_extensions_api#45] opened 2024-05-25 09:49 UTC
I recently ran into a conflict in seeing if I could use this library, where it strictly mandates Pandas 2+, but another library (the Apache IoTDB Python client) strictly required less than v2.  

I've already nudged them to see if they can put allowing v2 on their roadmap, but in their case it's possible that it is a more problematic effort (I haven't traced through how they convert thrift to dataframes).  

In the meantime I thought I'd check with you to see if the version requirement you have is intentional or accidental.  If accidental, then for a next release I'd like to request relaxing that Pandas version requirement to allow for something reasonably current in the Pandas 1.x series, like maybe 1.4 onwards.  Of course, if you know that you're actually depending on v2-specific functionality then the issue is moot.

I have workarounds for this, because I don't strictly have to have both of these libraries in use in the same venv or notebook.  Just passing along the observation in case you're interested in feedback that may suggest problems in adoption of your library.

Thanks!

**Comment by jenskeiner** [comment] 2024-05-27 13:59
Hi Reid,I think Pandas 2.x is not strictly necessary. I will relax the requirement with the next release which is coming soon.Best,JensAm 25.05.2024 um 11:49 schrieb Reid M. Pinchback ***@***.***>:﻿
I recently ran into a conflict in seeing if I could use this library, where it strictly mandates Pandas 2+, but another library (the Apache IoTDB Python client) strictly required less than v2.
I've already nudged them to see if they can put allowing v2 on their roadmap, but in their case it's possible that it is a more problematic effort (I haven't traced through how they convert thrift to dataframes).
In the meantime I thought I'd check with you to see if the version requirement you have is intentional or accidental.  If accidental, then for a next release I'd like to request relaxing that Pandas version requirement to allow for something reasonably current in the Pandas 1.x series, like maybe 1.4 onwards.  Of course, if you know that you're actually depending on v2-specific functionality then the issue is moot.
I have workarounds for this, because I don't strictly have to have both of these libraries in use in the same venv or notebook.  Just passing along the observation in case you're interested in feedback that may suggest problems in adoption of your library.
Thanks!

**Comment by rmpinchback** [comment] 2024-06-03 04:39
Awesome, ty.  The Apache iotdb team is relaxing their constraint as well, they hadn't spotted that it was accidentally constrained in setup.py in a way that differed from other configuration files (Python is such a joy when it comes to packaging lol).  Whatever you can do on your side will be welcome, as I've noticed that the collection of yfinance and calendar libraries can cause scipy dependencies to get downgraded when I work with various JupyterHub-friendly docker images.  I like how exchange calendars has evolved since last I used it, so thanks to you and others for the work to expand the feature set.

**Comment by jenskeiner** [comment] 2024-06-13 14:52
Closing this one because the latest version only requires Pandas >= 1.x.

**Closed as completed by jenskeiner** 2024-06-13 14:52 UTC
